### ISSUE TITLE
Unable to communicate with bootloader 

### ISSUE THREAD

**Issue by DeHHu** [ExpressLRS/ExpressLRS#373]
Hey guys, got this.

=================== FIRMWARE UPLOAD ===================
  Bin file '.pio\build\Frsky_RX_R9MX_via_BetaflightPassthrough\firmware.bin'
  Port COM5 @ 420000
======== PASSTHROUGH INIT ========
  Trying to initialize COM5 @ 420000
  Warning: 'No CLI available. Already in passthrough mode?'

Attempting to reboot into bootloader...
[1] retry...
    Bootloader type found : '=====================

BL_TYPE: R9MX

S'
    Got into bootloader after: 1 attempts
Wait sync...[FAILED] Unable to communicate with bootloader...
*** [upload] Exception : [FAILED] Unable to communicate with bootloader...

Traceback (most recent call last):
  File "C:\Users\DeHHu\.platformio\packages\tool-scons\scons-local-4.1.0\SCons\Action.py", line 1280, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "C:\elrs\ExpressLRS\src\python\UARTupload.py", line 219, in on_upload
    uart_upload(upload_port, firmware_path, upload_speed, ghst)
  File "C:\elrs\ExpressLRS\src\python\UARTupload.py", line 147, in uart_upload
    raise Exception(msg)
Exception: [FAILED] Unable to communicate with bootloader...

==================================== [FAILED] Took 29.32 seconds ====================================
Environment                              Status    Duration
---------------------------------------  --------  ------------
Frsky_RX_R9MX_via_BetaflightPassthrough  FAILED    00:00:29.320
=============================== 1 failed, 0 succeeded in 00:00:29.320 ===============================The terminal process "C:\Users\DeHHu\.platformio\penv\Scripts\platformio.exe 'run', '--target', 'upload', '--target', 'monitor', '--environment', 'Frsky_RX_R9MX_via_BetaflightPassthrough'" terminated with exit code: 1.

**Comment by DeHHu** [comment]
sorry, forgot push bind bitton on startup
